### ISSUE TITLE
我想加入这个的开发

### ISSUE THREAD

**Issue by byxiaobai** [StarWishsama/Slimefun4-Chinese-Version#1]
能不能给一下qq

**Comment by StarWishsama** [comment]
Emmm... 这只是把汉化后源码丢出来而已

想要加入 Slimefun 的开发请至 https://github.com/TheBusyBiscuit/Slimefun4 Pull Request哦

**Comment by byxiaobai** [comment]
..这个不是和他们的最新版本保持更新吗,我想改的就是这个汉化的

**Comment by byxiaobai** [comment]
不行就算了

**Comment by StarWishsama** [comment]
您去sf开发页面pr就行 如果作者同意后我也会跟进

**Comment by byxiaobai** [comment]
好吧，me.mrCookieSlime.Slimefun.api下的BlockStorage类中save(boolean computeChanges, boolean remove)有未翻译的地方

**Comment by StarWishsama** [comment]
收到
